#!/usr/bin/env python3
"""Bump the plugin version in plugin.json."""

import json
import sys
from pathlib import Path

PLUGIN_DIR = Path(__file__).resolve().parent
PLUGIN_JSON = PLUGIN_DIR / ".claude-plugin" / "plugin.json"
VERSION_GO = PLUGIN_DIR / "internal" / "version" / "version.go"

# FR-39: plugin.json is the single source of both version values, and the
# binary's own version reaches it through this generated, committed file. It is
# written here rather than passed as a build flag so that `go install` from the
# module path — FR-41's only supported provisioning path — yields a binary that
# knows its version with no -ldflags the user would have to remember.
VERSION_GO_TEMPLATE = """// Package version carries the binary's own version.
//
// GENERATED by bump-version.py from .claude-plugin/plugin.json — do not edit.
// FR-39 makes plugin.json the single source of both version values, so this
// file is rewritten and committed by `make bump-patch|bump-minor|bump-major`
// in the same commit and tag that moves the plugin version.
package version

// Version is the plugin version this binary was built at.
const Version = "{version}"
"""


def parse(version: str) -> tuple[int, int, int]:
    try:
        major, minor, patch = (int(x) for x in version.split("."))
    except ValueError:
        print(f"ERROR: {version!r} is not an X.Y.Z version", file=sys.stderr)
        sys.exit(1)
    return major, minor, patch


def bump(version: str, part: str) -> str:
    major, minor, patch = parse(version)
    if part == "major":
        return f"{major + 1}.0.0"
    if part == "minor":
        return f"{major}.{minor + 1}.0"
    if part == "patch":
        return f"{major}.{minor}.{patch + 1}"
    raise ValueError(f"Unknown part: {part}")


def update_json(path: Path, new_version: str) -> None:
    data = json.loads(path.read_text())
    data["version"] = new_version
    path.write_text(json.dumps(data, indent=2) + "\n")


def update_version_go(path: Path, new_version: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(VERSION_GO_TEMPLATE.format(version=new_version))


def usage() -> None:
    print(
        "Usage: bump-version.py <patch|minor|major>\n"
        "       bump-version.py set <X.Y.Z>        # explicit version (e.g. the 4.0.0 unification jump)\n"
        "       bump-version.py set-floor <X.Y.Z>  # advance minSddVersion (deliberate, per D-0015)\n"
        "\n"
        "Every mode edits .claude-plugin/plugin.json (the single version source);\n"
        "version modes also rewrite internal/version/version.go. The generated\n"
        "portable manifest is NOT touched here — run `make plugins` (the bump-*\n"
        "targets do) so portable/.codex-plugin/plugin.json picks the new values up.",
        file=sys.stderr,
    )
    sys.exit(1)


def main() -> None:
    args = sys.argv[1:]
    if len(args) == 1 and args[0] in ("patch", "minor", "major"):
        current = json.loads(PLUGIN_JSON.read_text())["version"]
        new_version = bump(current, args[0])
    elif len(args) == 2 and args[0] == "set":
        current = json.loads(PLUGIN_JSON.read_text())["version"]
        new_version = args[1]
        parse(new_version)  # validate shape
        if parse(new_version) <= parse(current):
            print(
                f"ERROR: set {new_version} does not move forward from {current} — "
                "plugin caches resolve by highest version, so a downgrade would never be served",
                file=sys.stderr,
            )
            sys.exit(1)
    elif len(args) == 2 and args[0] == "set-floor":
        floor = args[1]
        parse(floor)  # validate shape
        data = json.loads(PLUGIN_JSON.read_text())
        if parse(floor) < parse(data.get("minSddVersion", "0.0.0")):
            print(
                f"ERROR: set-floor {floor} lowers the floor from {data['minSddVersion']} — "
                "the floor only advances (D-0015)",
                file=sys.stderr,
            )
            sys.exit(1)
        if parse(floor) > parse(data["version"]):
            print(
                f"ERROR: floor {floor} exceeds the plugin version {data['version']} — "
                "no released binary could satisfy it",
                file=sys.stderr,
            )
            sys.exit(1)
        data["minSddVersion"] = floor
        PLUGIN_JSON.write_text(json.dumps(data, indent=2) + "\n")
        print(floor)
        return
    else:
        usage()
        return

    update_json(PLUGIN_JSON, new_version)
    update_version_go(VERSION_GO, new_version)

    print(new_version)


if __name__ == "__main__":
    main()
