#!/usr/bin/env python3
"""Bump the plugin version in plugin.json."""

import json
import sys
from pathlib import Path

PLUGIN_DIR = Path(__file__).resolve().parent
PLUGIN_JSON = PLUGIN_DIR / ".claude-plugin" / "plugin.json"
VERSION_GO = PLUGIN_DIR / "internal" / "version" / "version.go"

# FR-39: plugin.json is the single source of both version values, and the
# binary's own version reaches it through this generated, committed file. It is
# written here rather than passed as a build flag so that `go install` from the
# module path — FR-41's only supported provisioning path — yields a binary that
# knows its version with no -ldflags the user would have to remember.
VERSION_GO_TEMPLATE = """// Package version carries the binary's own version.
//
// GENERATED by bump-version.py from .claude-plugin/plugin.json — do not edit.
// FR-39 makes plugin.json the single source of both version values, so this
// file is rewritten and committed by `make bump-patch|bump-minor|bump-major`
// in the same commit and tag that moves the plugin version.
package version

// Version is the plugin version this binary was built at.
const Version = "{version}"
"""


def bump(version: str, part: str) -> str:
    major, minor, patch = (int(x) for x in version.split("."))
    if part == "major":
        return f"{major + 1}.0.0"
    if part == "minor":
        return f"{major}.{minor + 1}.0"
    if part == "patch":
        return f"{major}.{minor}.{patch + 1}"
    raise ValueError(f"Unknown part: {part}")


def update_json(path: Path, new_version: str) -> None:
    data = json.loads(path.read_text())
    data["version"] = new_version
    path.write_text(json.dumps(data, indent=2) + "\n")


def update_version_go(path: Path, new_version: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(VERSION_GO_TEMPLATE.format(version=new_version))


def main() -> None:
    if len(sys.argv) != 2 or sys.argv[1] not in ("patch", "minor", "major"):
        print("Usage: bump-version.py <patch|minor|major>", file=sys.stderr)
        sys.exit(1)

    part = sys.argv[1]
    current = json.loads(PLUGIN_JSON.read_text())["version"]
    new_version = bump(current, part)

    update_json(PLUGIN_JSON, new_version)
    update_version_go(VERSION_GO, new_version)

    print(new_version)


if __name__ == "__main__":
    main()
