package compile

// Rendered views (Designs/SddGraph DD-1, DD-2): the graph is the source of
// truth; phase markdown is a projection regenerated by compile, never
// hand-edited, never parsed back. Every generated file carries a marker
// naming the graph and the regenerating command, and the renderer REFUSES to
// overwrite any existing file that lacks the marker — that one rule is both
// the transition guard (a v1 hand-authored phase doc is never clobbered by
// accident; conversion takes it over explicitly, task 2.5) and the
// frozen-view refusal for hand-authored documents (a completed v1 phase's
// doc, anchored by a frozen review, is exactly such a file). Generated views
// have their own frozen-view rule (DD-2, task 4.1): a view rendered while
// every node in it was CLOSED (GREEN + covered by a passing frozen full
// review gate, the D-0022 completion-grade predicate) carries the
// frozen-view marker, and a later render that would CHANGE such a file is
// refused — byte-identical re-renders stay no-ops, so compile remains
// runnable on a completed plan. A legitimately reopened phase (a finding
// demoted a node after its gate recorded) requires removing the frozen view
// explicitly; the refusal names that escape.
//
// The plan README is treated differently from phase docs: its prose sections
// (Overview, Non-Goals, ...) and frontmatter are plan identity the graph
// does not hold, so the renderer performs exactly two surgical edits —
// initializing empty phases[] or refreshing statuses of proven graph-owned
// entries, and
// upserting one marker-delimited `## Graph View` section — and otherwise
// preserves the file byte-for-byte. Non-rendered (v1) phase entries retain
// their ownership and bytes; merging their membership is conversion's job.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/danweinerdev/claude-sdd-planner/v2/internal/graph/model"
	"github.com/danweinerdev/claude-sdd-planner/v2/internal/graph/states"
	"github.com/danweinerdev/claude-sdd-planner/v2/internal/rules"
	istore "github.com/danweinerdev/claude-sdd-planner/v2/internal/store"
	"gopkg.in/yaml.v3"
)

// frozenViewMarker marks a generated view rendered while every node in it
// was closed. Its presence turns content-changing regeneration into a
// refusal (DD-2's frozen-view invariant).
const frozenViewMarker = "<!-- FROZEN VIEW — every node in this phase is closed: GREEN and covered by a passing frozen full review gate. This projection is history; a render that would change it is refused. -->"

// viewMarker identifies a generated view. Its presence is the renderer's
// permission to overwrite; its absence on an existing target is a refusal.
// The prefix is owned by internal/rules (the validator keys SDD163's
// projection exemption on it), so emission and recognition cannot drift.
func viewMarker(plan string) string {
	return fmt.Sprintf("%s%s-Graph.json. Regenerate with `sdd compile --plan %s`. Edits here are overwritten. -->", rules.GeneratedViewMarkerPrefix, plan, plan)
}

// graphViewBegin/End delimit the README's upserted section. Owned by
// internal/rules: lifecycle normalization strips exactly these delimiters,
// so a frozen phase review's README pin survives the upsert.
const (
	graphViewBegin = rules.GraphViewBegin
	graphViewEnd   = rules.GraphViewEnd
)

// phaseGroup is one rendered phase: its ordinal, label, and nodes in
// declaration order.
type phaseGroup struct {
	Ordinal int
	Label   string
	Title   string
	Doc     string
	Nodes   []*model.Node
}

// groupPhases buckets nodes by their presentation label (DD-9: `phase` is a
// grouping consumed only by views), ordered by label with unlabeled nodes
// last as "Ungrouped".
func groupPhases(g *model.Graph, plan string) []phaseGroup {
	byLabel := map[string][]*model.Node{}
	var labels []string
	for i := range g.Nodes {
		n := &g.Nodes[i]
		if _, seen := byLabel[n.Phase]; !seen {
			labels = append(labels, n.Phase)
		}
		byLabel[n.Phase] = append(byLabel[n.Phase], n)
	}
	sort.SliceStable(labels, func(i, j int) bool {
		if (labels[i] == "") != (labels[j] == "") {
			return labels[j] == "" // unlabeled last
		}
		return labels[i] < labels[j]
	})
	var out []phaseGroup
	for i, label := range labels {
		title := label
		if title == "" {
			title = "Ungrouped"
		}
		ordinal := i + 1
		out = append(out, phaseGroup{
			Ordinal: ordinal,
			Label:   label,
			Title:   phaseTitle(title),
			Doc:     fmt.Sprintf("%02d-%s.md", ordinal, viewSlug(title)),
			Nodes:   byLabel[label],
		})
	}
	return out
}

var slugCleanRe = regexp.MustCompile(`[^A-Za-z0-9]+`)
var slugLeadingOrdinalRe = regexp.MustCompile(`^\d+-`)
var titleWordSplitRe = regexp.MustCompile(`[-_]+`)

// viewSlug turns a phase label into a filename component, dropping a leading
// `NN-` so a label like "01-core" does not double-number the doc.
func viewSlug(label string) string {
	s := slugLeadingOrdinalRe.ReplaceAllString(label, "")
	s = slugCleanRe.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if s == "" {
		s = "phase"
	}
	return s
}

// phaseTitle derives a human title from a raw phase label: strips a leading
// numeric prefix (`01-hermetic-git` -> `hermetic-git`), splits on `-`/`_`,
// and title-cases each word. The label itself (and the doc file stem
// viewSlug derives from it) is untouched — only the rendered title changes,
// so regenerating an existing plan does not move files.
func phaseTitle(label string) string {
	s := slugLeadingOrdinalRe.ReplaceAllString(label, "")
	if s == "" {
		return label
	}
	words := titleWordSplitRe.Split(s, -1)
	var out []string
	for _, w := range words {
		if w == "" {
			continue
		}
		out = append(out, strings.ToUpper(w[:1])+strings.ToLower(w[1:]))
	}
	if len(out) == 0 {
		return label
	}
	return strings.Join(out, " ")
}

// phaseStatus projects a group's frontmatter status: `complete` only when
// every node is CLOSED (the derived D-0022 predicate — never a stored flag,
// never hand-checked), `in-progress` once any node carries a claim or
// observation, else `planned`.
func phaseStatus(nodes []*model.Node, closed map[string]bool) string {
	if allClosed(nodes, closed) {
		return "complete"
	}
	for _, n := range nodes {
		if n.Claim != nil || n.Verification != nil {
			return "in-progress"
		}
	}
	return "planned"
}

// allClosed reports whether every node in the group derives closed.
func allClosed(nodes []*model.Node, closed map[string]bool) bool {
	if len(nodes) == 0 {
		return false
	}
	for _, n := range nodes {
		if !closed[n.ID] {
			return false
		}
	}
	return true
}

// renderPhaseDoc produces one phase view. created/updated are supplied by
// the writer so unchanged content stays byte-identical across days. st and
// closed carry the derived truth the view projects (DD-2: a projection may
// show derived state precisely because it is never parsed back).
func renderPhaseDoc(plan string, g *model.Graph, ph phaseGroup, created, updated string, st map[string]states.NodeState, closed map[string]bool) string {
	frozen := allClosed(ph.Nodes, closed)
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: \"%s\"\ntype: phase\nplan: \"%s\"\nphase: %d\nstatus: %s\n", ph.Title, plan, ph.Ordinal, phaseStatus(ph.Nodes, closed))
	fmt.Fprintf(&b, "created: %s\nupdated: %s\n", created, updated)
	fmt.Fprintf(&b, "deliverable: \"Graph view: %d node(s) under phase label %s\"\ntasks: []\n---\n\n", len(ph.Nodes), ph.Title)
	fmt.Fprintf(&b, "# Phase %d: %s\n\n%s\n\n", ph.Ordinal, ph.Title, viewMarker(plan))
	if frozen {
		fmt.Fprintf(&b, "%s\n\n", frozenViewMarker)
	}

	b.WriteString("## Overview\n\n")
	fmt.Fprintf(&b, "Rendered view of %d node(s) from the plan graph (schema v%d, seq %d).\n", len(ph.Nodes), g.Version, g.SeqCounter)
	b.WriteString("Observations shown are raw records; completion-grade closure derives from\nfull review gates and is never stored or hand-edited here.\n\n")

	b.WriteString("## Nodes\n")
	for _, n := range ph.Nodes {
		fmt.Fprintf(&b, "\n### %s\n\n", n.ID)
		fmt.Fprintf(&b, "- Contract: %s\n", n.Contract)
		fmt.Fprintf(&b, "- Justifies: %s\n", joinOr(n.Justifies, "(nothing — will not compile)"))
		fmt.Fprintf(&b, "- Depends on: %s\n", joinOr(n.Deps, "(nothing)"))
		fmt.Fprintf(&b, "- Gate: %s\n", describeGate(n.Gate))
		fmt.Fprintf(&b, "- Hazards: %s\n", describeHazards(n.Hazards))
		if len(n.Artifacts) > 0 {
			fmt.Fprintf(&b, "- Artifacts: %s\n", strings.Join(n.Artifacts, ", "))
		}
		if len(n.Inputs) > 0 {
			fmt.Fprintf(&b, "- Inputs: %s\n", describeInputs(n.Inputs))
		}
		fmt.Fprintf(&b, "- Estimate: %d\n", n.Estimate)
		if n.History != "" {
			fmt.Fprintf(&b, "- History: %s\n", n.History)
		}
		fmt.Fprintf(&b, "- Observation: %s\n", describeObservation(n.Verification))
		fmt.Fprintf(&b, "- Closure: %s\n", describeClosure(n.ID, st, closed))
		if n.Claim != nil {
			fmt.Fprintf(&b, "- Claim: %s (lease expires %s)\n", n.Claim.By, n.Claim.LeaseExpires)
		}
	}

	b.WriteString("\n## Acceptance Criteria\n\n")
	box := "[ ]"
	if frozen {
		box = "[x]"
	}
	fmt.Fprintf(&b, "- %s Every node in this phase is truly closed: a passing observation, and\n      coverage by a passing frozen full review gate (derived from the graph;\n      never checked off by hand).\n\n", box)
	b.WriteString("## Phase Completion Evidence\n\nPending — not complete.\n")
	return b.String()
}

// describeClosure projects the two-axis closure distinction (D-0022):
// closed vs assumed-closed for GREEN nodes, the derived state otherwise.
// A nil st/closed (a caller without derive inputs) reads as the zero state.
func describeClosure(id string, st map[string]states.NodeState, closed map[string]bool) string {
	switch {
	case closed[id]:
		return "**closed** — GREEN and covered by a passing frozen full review gate"
	case st[id].State == states.Green:
		return "assumed-closed — GREEN, not yet covered by a passing full review gate (sufficient to build on, not completion-grade)"
	case st[id].State == "":
		return "underived (no state inputs at render time)"
	default:
		return fmt.Sprintf("open — state %s", st[id].State)
	}
}

func joinOr(values []string, empty string) string {
	if len(values) == 0 {
		return empty
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = "`" + v + "`"
	}
	return strings.Join(quoted, ", ")
}

func describeGate(gate model.Gate) string {
	switch gate.Type {
	case model.GateTests:
		if len(gate.Tests) == 0 {
			return "tests (none named yet)"
		}
		var parts []string
		for _, t := range gate.Tests {
			s := fmt.Sprintf("`%s` in %s", t.ID, t.File)
			if len(t.Satisfies) > 0 {
				s += fmt.Sprintf(" (satisfies %s)", strings.Join(t.Satisfies, ", "))
			}
			parts = append(parts, s)
		}
		return "tests — " + strings.Join(parts, "; ")
	case model.GateCommand:
		return fmt.Sprintf("command — `%s`", gate.Command)
	case model.GateReview:
		if gate.Lanes == nil {
			return "review — full (carries completion-grade closure)"
		}
		return "review — lanes: " + strings.Join(gate.Lanes, ", ")
	case model.GateUnspecified:
		return "UNSPECIFIED (conversion sentinel; blocks compile until an operator states how this node is verified)"
	default:
		return gate.Type
	}
}

func describeHazards(h model.Hazards) string {
	switch {
	case h == nil:
		return "UNTRIAGED (blocks compile until resolved)"
	case len(h) == 0:
		return "none (explicit claim)"
	default:
		return strings.Join(h, ", ")
	}
}

// describeInputs renders a node's declared read-only inputs for views:
// `root:path` (whole file) or `root:path#Heading / Path` (section).
func describeInputs(inputs []model.Input) string {
	parts := make([]string, len(inputs))
	for i, in := range inputs {
		parts[i] = "`" + describeInputSpec(in) + "`"
	}
	return strings.Join(parts, ", ")
}

func describeObservation(v *model.Verification) string {
	if v == nil {
		return "none yet"
	}
	s := fmt.Sprintf("**%s** at seq %d — isolation %s", v.Result, v.Seq, v.Isolation)
	if v.Provenance != nil {
		p := v.Provenance.Kind
		if v.Provenance.Revision != "" {
			p += " " + shortRev(v.Provenance.Revision)
		}
		if v.Provenance.Changelist != "" {
			p += " CL " + v.Provenance.Changelist
		}
		s += ", provenance " + p
	}
	return s
}

func shortRev(rev string) string {
	if len(rev) > 12 {
		return rev[:12]
	}
	return rev
}

var (
	createdLineRe = regexp.MustCompile(`(?m)^created: (\S+)`)
	updatedLineRe = regexp.MustCompile(`(?m)^updated: (\S+)`)
	// planEvidenceHeadingRe locates the evidence section the graph-view
	// insertion must stay ahead of.
	planEvidenceHeadingRe = regexp.MustCompile(`(?m)^## Plan Completion Evidence\s*$`)
)

// planWrite decides one view target's fate without writing: whether a write
// is needed, and the exact bytes to write. It carries BOTH refusal rules —
// an existing non-generated file (hand-authored or frozen v1 history), and
// an existing FROZEN VIEW whose content would change (DD-2: a projection of
// closed work is history; byte-identical re-renders stay no-ops). Shared by
// preflight (dry-run, before the graph write) and writeView, so a refusal
// can never fire after the graph moved.
func planWrite(path, content, plan string) (write bool, filled string, err error) {
	today := time.Now().Format("2006-01-02")
	existing, readErr := os.ReadFile(path)
	if readErr != nil {
		if !os.IsNotExist(readErr) {
			return false, "", readErr
		}
		return true, fillDates(content, today, today), nil
	}
	if !strings.Contains(string(existing), viewMarker(plan)) {
		return false, "", fmt.Errorf("compile: %s exists and is not a generated view; refusing to overwrite it (a hand-authored or frozen document is taken over by `sdd graph convert`, never clobbered by a render)", path)
	}
	created := today
	if m := createdLineRe.FindStringSubmatch(string(existing)); m != nil {
		created = m[1]
	}
	prevUpdated := today
	if m := updatedLineRe.FindStringSubmatch(string(existing)); m != nil {
		prevUpdated = m[1]
	}
	// Byte-stability check: same content under the existing stamps means no
	// write at all — and therefore no frozen-view refusal either, so
	// compile stays runnable on a completed plan.
	if fillDates(content, created, prevUpdated) == string(existing) {
		return false, "", nil
	}
	if strings.Contains(string(existing), frozenViewMarker) {
		return false, "", fmt.Errorf("compile: %s is a frozen view — every node in it was closed when it was rendered, and the graph now disagrees with that frozen history; if the phase was legitimately reopened (a review finding demoted a node), delete the frozen view file explicitly and recompile", path)
	}
	return true, fillDates(content, created, today), nil
}

// writeView writes one rendered view with date stability: an existing
// generated view keeps its created date, and keeps its bytes entirely when
// nothing but the updated stamp would change.
func writeView(path, content, plan string) (wrote bool, err error) {
	write, filled, err := planWrite(path, content, plan)
	if err != nil || !write {
		return false, err
	}
	return true, istore.WriteAtomic(path, filled)
}

// fillDates substitutes the renderer's date placeholders.
func fillDates(content, created, updated string) string {
	content = strings.Replace(content, "created: {DATE}", "created: "+created, 1)
	return strings.Replace(content, "updated: {DATE}", "updated: "+updated, 1)
}

// preflightViews dry-runs every render target before anything is written:
// both refusal rules (non-generated file in a target's place, frozen view
// whose content would change) fire here, BEFORE the graph write, leaving
// nothing half-done.
func preflightViews(root, plan string, g *model.Graph, st map[string]states.NodeState, closed map[string]bool) error {
	planDir := filepath.Join(root, "Plans", plan)
	for _, ph := range groupPhases(g, plan) {
		path := filepath.Join(planDir, ph.Doc)
		content := renderPhaseDoc(plan, g, ph, "{DATE}", "{DATE}", st, closed)
		if _, _, err := planWrite(path, content, plan); err != nil {
			return err
		}
	}
	_, _, err := planReadmeUpdate(planDir, plan, groupPhases(g, plan), closed)
	return err
}

// renderViews writes the phase views and updates the README projection.
func renderViews(root, plan string, g *model.Graph, st map[string]states.NodeState, closed map[string]bool) ([]string, error) {
	planDir := filepath.Join(root, "Plans", plan)
	groups := groupPhases(g, plan)
	if err := preflightViews(root, plan, g, st, closed); err != nil {
		return nil, err
	}
	// Determine ownership before writing phase files: a just-created marker
	// must not retroactively authorize taking over an existing manual entry.
	readmeBefore, err := os.ReadFile(filepath.Join(planDir, "README.md"))
	if err != nil {
		return nil, err
	}
	readme, readmeChanged, err := planReadmeUpdate(planDir, plan, groups, closed)
	if err != nil {
		return nil, err
	}

	var written []string
	for _, ph := range groups {
		path := filepath.Join(planDir, ph.Doc)
		// Dates stay templated here; writeView fills them with stability
		// rules (existing created preserved, updated stamped on change).
		content := renderPhaseDoc(plan, g, ph, "{DATE}", "{DATE}", st, closed)
		wrote, err := writeView(path, content, plan)
		if err != nil {
			return nil, err
		}
		if wrote {
			written = append(written, path)
		}
	}

	if readmeChanged {
		if err := istore.WriteAtomicExpecting(filepath.Join(planDir, "README.md"), readme, istore.Digest(string(readmeBefore))); err != nil {
			return nil, err
		}
		written = append(written, filepath.Join(planDir, "README.md"))
	}
	return written, nil
}

// updateReadme applies the preflightable, surgical README projection.
func updateReadme(planDir, plan string, groups []phaseGroup, closed map[string]bool) (bool, error) {
	before, err := os.ReadFile(filepath.Join(planDir, "README.md"))
	if err != nil {
		return false, err
	}
	out, changed, err := planReadmeUpdate(planDir, plan, groups, closed)
	if err != nil || !changed {
		return false, err
	}
	return true, istore.WriteAtomicExpecting(filepath.Join(planDir, "README.md"), out, istore.Digest(string(before)))
}

func planReadmeUpdate(planDir, plan string, groups []phaseGroup, closed map[string]bool) (string, bool, error) {
	path := filepath.Join(planDir, "README.md")
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", false, fmt.Errorf("compile: reading plan README: %w", err)
	}
	src := string(raw)
	out := src

	out, err = refreshReadmePhaseStatuses(planDir, plan, out, groups, closed)
	if err != nil {
		return "", false, err
	}

	section := renderGraphViewSection(plan, groups)
	if begin := strings.Index(out, graphViewBegin); begin >= 0 {
		end := strings.Index(out, graphViewEnd)
		if end < begin {
			return "", false, fmt.Errorf("compile: %s has a malformed graph-view section (begin without end)", path)
		}
		out = out[:begin] + section + out[end+len(graphViewEnd):]
	} else if i := planEvidenceHeadingRe.FindStringIndex(out); i != nil {
		// Insert BEFORE the Plan Completion Evidence section, never after:
		// evidence writers replace that section's whole extent (up to the
		// next depth<=2 heading), and the begin marker is a comment, not a
		// heading — a section appended after the evidence heading gets its
		// begin marker swallowed by the next evidence write, orphaning the
		// projection from the lifecycle strip that keeps frozen review
		// pins honest.
		out = out[:i[0]] + section + "\n\n" + out[i[0]:]
	} else {
		if !strings.HasSuffix(out, "\n") {
			out += "\n"
		}
		out += "\n" + section + "\n"
	}

	if out == src {
		return "", false, nil
	}
	// A real change restamps the README's updated date; an unchanged README
	// is never touched, so idempotent re-renders stay byte-stable.
	end, err := readmeFrontmatterEnd(out)
	if err != nil {
		return "", false, err
	}
	out = updatedLineRe.ReplaceAllString(out[:end], "updated: "+time.Now().Format("2006-01-02")) + out[end:]
	return out, true, nil
}

func readmeFrontmatterEnd(src string) (int, error) {
	if !strings.HasPrefix(src, "---\n") {
		return 0, fmt.Errorf("compile: README requires YAML frontmatter")
	}
	at := strings.Index(src[4:], "\n---\n")
	if at < 0 {
		return 0, fmt.Errorf("compile: README frontmatter is not closed")
	}
	return 4 + at + 1, nil // beginning of the closing delimiter
}

// refreshReadmePhaseStatuses changes only the owned scalar tokens. YAML node
// positions keep comments, quoting, extra fields, flow style and identity prose
// intact instead of serializing the entire frontmatter through a flat model.
func refreshReadmePhaseStatuses(planDir, plan, src string, groups []phaseGroup, closed map[string]bool) (string, error) {
	end, err := readmeFrontmatterEnd(src)
	if err != nil {
		return "", err
	}
	fm := src[4:end]
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(fm), &doc); err != nil {
		return "", fmt.Errorf("compile: invalid README YAML: %w", err)
	}
	if len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		return "", fmt.Errorf("compile: README frontmatter must be a mapping")
	}
	var phases, key *yaml.Node
	for i := 0; i < len(doc.Content[0].Content); i += 2 {
		if doc.Content[0].Content[i].Value == "phases" {
			if phases != nil {
				return "", fmt.Errorf("compile: duplicate README phases field")
			}
			key, phases = doc.Content[0].Content[i], doc.Content[0].Content[i+1]
		}
	}
	if phases == nil {
		return src, nil
	}
	if phases.Kind != yaml.SequenceNode {
		return "", fmt.Errorf("compile: README phases must be a sequence")
	}
	offset := func(n *yaml.Node) (int, error) {
		at := 4
		for line := 1; line < n.Line; line++ {
			next := strings.IndexByte(src[at:end], '\n')
			if next < 0 {
				return 0, fmt.Errorf("compile: invalid phase source position")
			}
			at += next + 1
		}
		// YAML columns count Unicode code points, not bytes.
		for column := 1; column < n.Column; column++ {
			if at >= end {
				return 0, fmt.Errorf("compile: invalid phase source column")
			}
			_, size := utf8.DecodeRuneInString(src[at:end])
			at += size
		}
		return at, nil
	}
	if len(phases.Content) == 0 && len(groups) > 0 {
		start, err := offset(key)
		if err != nil {
			return "", err
		}
		value, err := offset(phases)
		if err != nil {
			return "", err
		}
		lineEnd := strings.IndexByte(src[value:end], '\n')
		if lineEnd < 0 {
			return "", fmt.Errorf("compile: unsupported empty phases layout")
		}
		lineEnd += value
		close := strings.IndexByte(src[value:lineEnd], ']')
		if close < 0 || src[value] != '[' || strings.TrimSpace(src[value+1:value+close]) != "" {
			return "", fmt.Errorf("compile: empty phases must use [] on one line")
		}
		close += value
		var b strings.Builder
		b.WriteString(strings.TrimRight(src[start:value], " \t"))
		b.WriteString(src[close+1 : lineEnd])
		b.WriteByte('\n')
		for _, ph := range groups {
			fmt.Fprintf(&b, "  - id: %d\n    title: %s\n    status: %s\n    doc: %s\n", ph.Ordinal, strconv.Quote(ph.Title), phaseStatus(ph.Nodes, closed), strconv.Quote(ph.Doc))
		}
		return src[:start] + b.String() + src[lineEnd+1:], nil
	}
	type edit struct {
		start, end int
		text       string
	}
	var edits []edit
	for _, entry := range phases.Content {
		if entry.Kind != yaml.MappingNode {
			continue
		}
		fields := map[string]*yaml.Node{}
		for i := 0; i < len(entry.Content); i += 2 {
			k := entry.Content[i].Value
			if fields[k] != nil {
				return "", fmt.Errorf("compile: duplicate phase field %q", k)
			}
			fields[k] = entry.Content[i+1]
		}
		if fields["id"] == nil || fields["doc"] == nil {
			continue
		}
		for _, ph := range groups {
			if fields["doc"].Value != ph.Doc {
				continue
			}
			old, err := os.ReadFile(filepath.Join(planDir, ph.Doc))
			if os.IsNotExist(err) {
				continue
			}
			if err != nil {
				return "", err
			}
			if !strings.Contains(string(old), viewMarker(plan)) {
				continue
			}
			if fields["id"].Value != strconv.Itoa(ph.Ordinal) {
				return "", fmt.Errorf("compile: generated phase %s has README id %q, expected %d; reconcile the identity instead of silently leaving a stale status", ph.Doc, fields["id"].Value, ph.Ordinal)
			}
			status := fields["status"]
			want := phaseStatus(ph.Nodes, closed)
			if status != nil && status.Kind == yaml.ScalarNode && status.Tag == "!!str" && status.Value == want {
				continue
			}
			if status == nil || status.Kind != yaml.ScalarNode || status.Tag != "!!str" || status.Anchor != "" || status.Style&(yaml.LiteralStyle|yaml.FoldedStyle|yaml.TaggedStyle) != 0 {
				return "", fmt.Errorf("compile: generated phase %s requires a plain or quoted scalar status", ph.Doc)
			}
			start, err := offset(status)
			if err != nil {
				return "", err
			}
			finish := start
			replacement := want
			switch status.Style {
			case yaml.DoubleQuotedStyle, yaml.SingleQuotedStyle:
				quote := src[start]
				if quote != '"' && quote != '\'' {
					return "", fmt.Errorf("compile: quoted phase status source span does not start at a quote")
				}
				finish++
				for finish < end {
					if quote == '"' && src[finish] == '\\' {
						finish += 2
						continue
					}
					if src[finish] == quote {
						if quote == '\'' && finish+1 < end && src[finish+1] == '\'' {
							finish += 2
							continue
						}
						finish++
						break
					}
					finish++
				}
				if finish > end || src[finish-1] != quote {
					return "", fmt.Errorf("compile: unterminated phase status")
				}
				if quote == '"' {
					replacement = strconv.Quote(want)
				} else {
					replacement = "'" + want + "'"
				}
			default:
				if !strings.HasPrefix(src[start:end], status.Value) || strings.ContainsAny(status.Value, "\r\n") {
					return "", fmt.Errorf("compile: unsafe phase status source span")
				}
				finish = start + len(status.Value)
			}
			edits = append(edits, edit{start, finish, replacement})
		}
	}
	sort.Slice(edits, func(i, j int) bool { return edits[i].start > edits[j].start })
	for _, e := range edits {
		src = src[:e.start] + e.text + src[e.end:]
	}
	return src, nil
}

func renderGraphViewSection(plan string, groups []phaseGroup) string {
	var b strings.Builder
	b.WriteString(graphViewBegin + "\n\n## Graph View\n\n")
	fmt.Fprintf(&b, "%s\n\n", viewMarker(plan))
	b.WriteString("| Phase | Nodes | Doc |\n|---|---|---|\n")
	total := 0
	for _, ph := range groups {
		fmt.Fprintf(&b, "| %d: %s | %d | `%s` |\n", ph.Ordinal, ph.Title, len(ph.Nodes), ph.Doc)
		total += len(ph.Nodes)
	}
	fmt.Fprintf(&b, "\n%d node(s) total. The committed graph (`%s-Graph.json`) is the source of\ntruth; these documents are projections.\n\n", total, plan)
	b.WriteString(graphViewEnd)
	return b.String()
}

// PathForView is exported for tests and callers that need to know where a
// phase group renders.
func PathForView(root, plan, doc string) string {
	return filepath.Join(root, "Plans", plan, doc)
}
