// Package version carries the binary's own version.
//
// GENERATED by bump-version.py from .claude-plugin/plugin.json — do not edit.
// FR-39 makes plugin.json the single source of both version values, so this
// file is rewritten and committed by `make bump-patch|bump-minor|bump-major`
// in the same commit and tag that moves the plugin version.
package version

// Version is the plugin version this binary was built at.
const Version = "2.2.0"
