package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/danweinerdev/claude-sdd-planner/v2/internal/hook"
	"github.com/danweinerdev/claude-sdd-planner/v2/internal/provision"
)

// `sdd hook` implements the plugin's Claude Code hooks (FR-27/28/44),
// replacing hooks/reviewer-bash-guard.py and hooks/load-decisions.sh.
//
// Both subcommands fail open on every error path and always exit 0. A hook
// that exits nonzero or emits malformed JSON degrades the session for every
// later call, which is a worse outcome than a missed denial — the behavioral
// guidance in each agent's prompt remains the primary control.

type hookPayload struct {
	AgentType string `json:"agent_type"`
	ToolName  string `json:"tool_name"`
	ToolInput struct {
		Command  string `json:"command"`
		FilePath string `json:"file_path"`
	} `json:"tool_input"`
	CWD string `json:"cwd"`
}

func cmdHook(event string) error {
	switch event {
	case "pretooluse":
		return hookPreToolUse()
	case "sessionstart":
		return hookSessionStart()
	default:
		return fmt.Errorf("hook: unknown event %q; expected `pretooluse` or `sessionstart`", event)
	}
}

func hookPreToolUse() error {
	raw, err := io.ReadAll(os.Stdin)
	if err != nil {
		return nil // fail open
	}
	var payload hookPayload
	if json.Unmarshal(raw, &payload) != nil {
		return nil
	}

	var decision hook.Decision
	switch payload.ToolName {
	case "Bash":
		decision = hook.CheckBash(payload.AgentType, payload.ToolInput.Command)
	case "Write", "Edit", "NotebookEdit":
		decision = hook.CheckWrite(payload.AgentType, payload.ToolName,
			payload.ToolInput.FilePath, projectDir(payload))
	}
	if !decision.Deny {
		return nil
	}

	out, err := json.Marshal(map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":            "PreToolUse",
			"permissionDecision":       "deny",
			"permissionDecisionReason": decision.Reason,
		},
	})
	if err != nil {
		return nil
	}
	fmt.Println(string(out))
	return nil
}

func hookSessionStart() error {
	raw, _ := io.ReadAll(os.Stdin)
	var payload hookPayload
	_ = json.Unmarshal(raw, &payload)

	context := hook.SessionStartContext(projectDir(payload))

	// A stale hooks.json is invisible by construction: the events it does
	// declare keep firing, so nothing looks broken while a newly added event
	// silently never runs. SessionStart is the one hook guaranteed to fire
	// once per session, and it is already generated by the same code that
	// knows the correct shape — so it is the natural place to say so.
	//
	// Reported as context rather than an error: the session is usable, and a
	// hook that failed here would be a worse outcome than the drift it is
	// reporting (D-0013).
	if notice := hooksDriftNotice(); notice != "" {
		if context == "" {
			context = notice
		} else {
			context += "\n\n" + notice
		}
	}

	if context == "" {
		return nil
	}
	out, err := json.Marshal(map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     "SessionStart",
			"additionalContext": context,
		},
	})
	if err != nil {
		return nil
	}
	fmt.Println(string(out))
	return nil
}

// projectDir prefers the payload's cwd, then CLAUDE_PROJECT_DIR, then the
// process working directory — the same order the shell hook used.
func projectDir(p hookPayload) string {
	if p.CWD != "" {
		return p.CWD
	}
	if env := os.Getenv("CLAUDE_PROJECT_DIR"); env != "" {
		return env
	}
	wd, _ := os.Getwd()
	return wd
}

// hooksDriftNotice returns a one-line warning when the installed hooks.json is
// not what this binary would generate, or "" when it is current, absent
// (an unprovisioned install is a documented state, not drift), or
// unknowable.
func hooksDriftNotice() string {
	root := os.Getenv("CLAUDE_PLUGIN_ROOT")
	if root == "" {
		return ""
	}
	state, err := provision.CheckHooks(root)
	if err != nil || state != provision.HooksStale {
		return ""
	}
	return "> **sdd hooks are out of date.** The installed `hooks.json` does not match " +
		"this plugin version's hook set, so an event it declares may not be firing. " +
		"Run `/sdd-planner:setup` (or `sdd provision`) to regenerate it, then restart the session."
}
