package provision

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// Hook installation.
//
// hooks.json has no OS conditional: every command it lists runs on every
// platform. Shipping one entry per platform therefore guarantees that the
// wrong one fails on each — `sdd.exe: No such file or directory` on Linux,
// or `powershell: command not found` — and Claude Code surfaces that as a
// hook error on every tool call. The noise is constant and, because the
// surviving entry did its job, entirely meaningless.
//
// So hooks.json is generated rather than shipped: provisioning knows which
// platform it is running on and writes exactly one command per event, naming
// the interpreter and wrapper that exist here. Both wrappers ship in the
// plugin; only the applicable one is ever referenced.
//
// This runs on every `sdd provision`, which /setup performs on every run, so
// a plugin upgrade regenerates the file for the machine installing it.

// hookEvent is one event and the sdd subcommand that serves it.
type hookEvent struct {
	Name       string // Claude Code's event name
	Matcher    string // tool matcher, "*" for all
	Subcommand string // `sdd hook <subcommand>`
	StatusText string // optional progress text
}

var hookEvents = []hookEvent{
	{Name: "SessionStart", Matcher: "*", Subcommand: "sessionstart",
		StatusText: "Loading decision ledger..."},
	{Name: "PreToolUse", Matcher: "Bash|Write|Edit|NotebookEdit", Subcommand: "pretooluse"},
}

// hookCommand builds the command string for one event on this platform.
//
// ${CLAUDE_PLUGIN_ROOT} stays uninterpolated: Claude Code expands it at hook
// time, and it is the only variable it expands. Writing an absolute path here
// instead would bake in the cache directory of the version that generated the
// file, which is exactly the staleness this whole change removes.
func hookCommand(ev hookEvent) string {
	if runtime.GOOS == "windows" {
		return fmt.Sprintf(
			`powershell -NoProfile -ExecutionPolicy Bypass -File "${CLAUDE_PLUGIN_ROOT}/hooks/sdd-hook.ps1" %s`,
			ev.Subcommand)
	}
	return fmt.Sprintf(`sh "${CLAUDE_PLUGIN_ROOT}/hooks/sdd-hook.sh" %s`, ev.Subcommand)
}

// hooksDocument is hooks.json's shape. Written through encoding/json rather
// than a text template so the output is always valid JSON.
type hooksDocument struct {
	Comment string                   `json:"_comment"`
	Hooks   map[string][]hookMatcher `json:"hooks"`
}

type hookMatcher struct {
	Matcher string      `json:"matcher"`
	Hooks   []hookEntry `json:"hooks"`
}

type hookEntry struct {
	Type          string `json:"type"`
	Command       string `json:"command"`
	Timeout       int    `json:"timeout"`
	StatusMessage string `json:"statusMessage,omitempty"`
}

const hooksComment = "GENERATED by `sdd provision` for this platform — do not edit. " +
	"hooks.json has no OS conditional, so listing every platform's command would " +
	"make the inapplicable ones fail on every tool call. Re-run `sdd provision` " +
	"(or /setup) to regenerate."

// InstallHooks writes hooks.json for the current platform. It is idempotent:
// identical content is left untouched so an unchanged file keeps its mtime.
func InstallHooks(pluginRoot string) (path string, wrote bool, err error) {
	doc := hooksDocument{Comment: hooksComment, Hooks: map[string][]hookMatcher{}}
	for _, ev := range hookEvents {
		doc.Hooks[ev.Name] = []hookMatcher{{
			Matcher: ev.Matcher,
			Hooks: []hookEntry{{
				Type:          "command",
				Command:       hookCommand(ev),
				Timeout:       10,
				StatusMessage: ev.StatusText,
			}},
		}}
	}

	body, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", false, fmt.Errorf("rendering hooks.json: %w", err)
	}
	body = append(body, '\n')

	path = filepath.Join(pluginRoot, "hooks", "hooks.json")
	if current, err := os.ReadFile(path); err == nil && string(current) == string(body) {
		return path, false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", false, fmt.Errorf("creating %s: %w", filepath.Dir(path), err)
	}
	// Same temp-then-rename discipline as the binary copy: a hook firing
	// mid-write must never read a partial hooks.json.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return "", false, fmt.Errorf("writing %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return "", false, fmt.Errorf("installing %s: %w", path, err)
	}
	// The POSIX wrapper must be executable even if the packaging lost the bit.
	if runtime.GOOS != "windows" {
		_ = os.Chmod(filepath.Join(pluginRoot, "hooks", "sdd-hook.sh"), 0o755)
	}
	return path, true, nil
}
